# version: '3.8' (obsolete?)

networks:
  backend_network:
    driver: bridge
  frontend_network:
    driver: bridge
    
services:

  # MySQL Database Service
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: processdb
      MYSQL_USER: base_user
      MYSQL_PASSWORD: base_user
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
    networks:
      - backend_network

  # Spring Boot Application (Backend)
  spring-boot-app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: spring-boot-app
    restart: always
    ports:
      - "8081:8081"
    depends_on:
      - mysql
    networks:
      - backend_network
      - frontend_network

  # Vue.js Application (Frontend)
  vue-app:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: vue-app
    restart: always
    ports:
      - "5173:5173"
    depends_on:
      - spring-boot-app
    networks:
      - frontend_network

volumes:
  db:
