# version: '3.8' (obsolete?)

networks:
  backend_network:
    driver: bridge
  frontend_network:
    driver: bridge
    
services:

  # MySQL Database Service
  mysql:
    image: mysql:latest
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: processdb
      # MYSQL_USER: base_user
      # MYSQL_PASSWORD: base_user
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
    networks:
      - backend_network

  # Spring Boot Application (Backend)
  spring-boot-app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: spring-boot-app
    restart: always
    environment:
      SPRING_APPLICATION_JSON: '{
      "spring.datasource.url": "jdbc:mysql://mysql:3306/processdb?allowPublicKeyRetrieval=true&useSSL=false",
      "spring.datasource.username": "root",
      "spring.datasource.password": "123456",
      "spring.jpa.hibernate.ddl-auto": "update"
      }'
    ports:
      - "8081:8081"
    depends_on:
      - mysql
    networks:
      - backend_network
      - frontend_network

  # Vue.js Application (Frontend)
  vue-app:
    build:
      context: ./frontend
    image: nginx:latest
    container_name: vue-app
    restart: always
    volumes:
      - ./vue-app/dist:/usr/share/nginx/html
    ports:
      - "5173:5173"
    depends_on:
      - spring-boot-app
    networks:
      - frontend_network

volumes:
  db:
